import { createFileRoute, Link } from "@tanstack/react-router";
import { Boxes, Bot, GitBranch, Route as RouteIcon, Target, Wrench } from "lucide-react";
import { AppHeader } from "@/components/AppHeader";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import heroImage from "@/assets/forge-hero.jpg";

export const Route = createFileRoute("/")({
  component: Landing,
});

const FEATURES = [
  {
    icon: Target,
    title: "Skill assessment",
    text: "Answer questions across Python, Web, Git, DevOps, AI and Database to get a scored profile.",
  },
  {
    icon: RouteIcon,
    title: "Career roadmap",
    text: "Current level → skill gap → topics → projects → resources → target role, generated by AI.",
  },
  {
    icon: Bot,
    title: "RAG assistant",
    text: "Every answer is grounded in a curated knowledge base of courses, projects and roadmaps.",
  },
  {
    icon: Wrench,
    title: "Career agent",
    text: "An agent that calls real tools to analyze your skills, compute gaps and build your plan.",
  },
  {
    icon: Boxes,
    title: "Portfolio",
    text: "Track projects, certifications and progress bars that show how close you are to your goal.",
  },
  {
    icon: GitBranch,
    title: "Mentor console",
    text: "Mentors and admins review students, publish resources and author assessment questions.",
  },
];

function Landing() {
  return (
    <div className="min-h-screen">
      <AppHeader />

      <main>
        <section className="relative overflow-hidden">
          <img
            src={heroImage}
            alt="Glowing circuit pathways forming a rising career roadmap"
            width={1600}
            height={1000}
            className="absolute inset-0 h-full w-full object-cover opacity-30"
          />
          <div className="relative mx-auto max-w-4xl px-4 py-24 text-center">
            <p className="text-xs uppercase tracking-[0.3em] text-accent">AI career engineering</p>
            <h1 className="mt-4 font-display text-5xl font-semibold leading-tight sm:text-6xl">
              Know exactly <span className="gradient-text">what to learn next</span>
            </h1>
            <p className="mx-auto mt-5 max-w-2xl text-base text-muted-foreground">
              SkillForge assesses the skills you already have, measures the distance to the tech role you want, and
              forges a staged roadmap of topics, projects and resources — with an AI assistant grounded in a real
              knowledge base.
            </p>
            <div className="mt-8 flex flex-wrap justify-center gap-3">
              <Button asChild size="lg">
                <Link to="/auth">Build my roadmap</Link>
              </Button>
              <Button asChild size="lg" variant="outline">
                <Link to="/dashboard">Open dashboard</Link>
              </Button>
            </div>
          </div>
        </section>

        <section className="mx-auto max-w-6xl px-4 py-16">
          <h2 className="font-display text-2xl font-semibold">Everything a student needs to get hired</h2>
          <div className="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">
            {FEATURES.map((f) => (
              <Card key={f.title} className="surface-panel border-border/70">
                <CardHeader>
                  <f.icon className="h-6 w-6 text-primary" />
                  <CardTitle className="mt-3 text-lg">{f.title}</CardTitle>
                  <CardDescription>{f.text}</CardDescription>
                </CardHeader>
              </Card>
            ))}
          </div>
        </section>

        <section className="mx-auto max-w-4xl px-4 pb-24">
          <Card className="surface-panel glow-ring border-primary/30">
            <CardHeader>
              <CardTitle>The SkillForge journey</CardTitle>
              <CardDescription>Six steps from unsure to job-ready.</CardDescription>
            </CardHeader>
            <CardContent>
              <ol className="grid gap-3 text-sm sm:grid-cols-2">
                {[
                  "Create your student profile",
                  "Add skills, projects and certifications",
                  "Take the skill assessment",
                  "Review your skill gaps",
                  "Generate your AI roadmap",
                  "Ask the assistant and career agent",
                ].map((step, i) => (
                  <li key={step} className="flex items-center gap-3 rounded-md border border-border/60 px-3 py-2">
                    <span className="flex h-6 w-6 items-center justify-center rounded-full bg-primary text-xs font-bold text-primary-foreground">
                      {i + 1}
                    </span>
                    {step}
                  </li>
                ))}
              </ol>
            </CardContent>
          </Card>
        </section>
      </main>

      <footer className="border-t border-border/70 py-8 text-center text-xs text-muted-foreground">
        SkillForge · AI-powered skill gap analysis and career roadmaps
      </footer>
    </div>
  );
}
